logging:
    level:
      org.springframework: ERROR
      com.example: DEBUG
   
---

spring: 
  datasource:
    url: jdbc:h2:mem:fileuploaddemo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
      
---

application:
  fileUploadLocation: c://temp//
  name: fileupload
  errors:
    - code: F01
      description: Error writing to a file
      severity: Severe
    - code: F02
      description: Error saving to the database
      severity: Severe 
    - code: F03
      description: Unkown Error encountered, please report to the vendor
      severity: Severe
    - code: F04
      description: File is empty, please select a file
      severity: Severe
    - code: F05
      description: File size exceeds permissible limits of 10 MB
      severity: Severe

       