logging:
    level:
      org.springframework: ERROR
      com.example: DEBUG
   
---
   
 spring:
    datasource:
      url: jdbc:h2:mem:fileuploaddemo;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
      driverClassName: org.h2.Driver
      