logging:
    level:
      org.springframework: ERROR
      com.example: DEBUG
   
---

spring: 
  datasource:
    url: jdbc:h2:mem:fileuploaddemo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
      
---

application:
  fileUploadLocation: c://fileupload
  errors:
    - code: 11
      description: error1
    - code: 12
      description: error2
    - code: 1
      description: error3
  name: fileupload

       